# .github/workflows/football_scraper_workflow.yml
name: Daily Football Scraper ⚽

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape-football-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest stable Python 3.x

    - name: Install dependencies (including certifi update)
      run: |
        python -m pip install --upgrade pip
        # Upgrade certifi explicitly before installing other requirements
        pip install --upgrade certifi
        pip install -r requirements.txt

    - name: Run Football Scraper
      run: |
        python LUCILAND.PY # Your script name

    - name: Commit changes (if any)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add live_events.json football_scraper.log # Add your output files
        git commit -m "chore: Auto-update: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
