# .github/workflows/football_scraper_workflow.yml
name: Daily Football Scraper ⚽

on:
  schedule:
    # Runs every 3 hours
    # The timezone is UTC by default for cron expressions in GitHub Actions.
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape-football-data:
    runs-on: ubuntu-latest
    # Add these permissions to allow the GITHUB_TOKEN to push code
    permissions:
      contents: write # This grants write access to the repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Football Scraper
      run: |
        python  LUCILAND.PY

    - name: Commit changes (if any)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add live_events.json scraper.log
        git commit -m "chore: Auto-update: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
