# .github/workflows/LUCILAND.yml
name: LUCILAND Football Scraper ⚽
on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours (fixed cron syntax)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape-football-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the repository contents
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Use Python 3.11 for better SSL support
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Upgrade SSL-related packages explicitly
        pip install --upgrade certifi urllib3 requests
        # Install other requirements if they exist
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run LUCILAND Football Scraper
      run: |
        python LUCILAND.PY
      env:
        PYTHONHTTPSVERIFY: 0  # Disable SSL verification as fallback
        
    - name: Commit changes (if any)
      run: |
        git config user.name "LUCILAND-bot"
        git config user.email "luciland-bot@users.noreply.github.com"
        git add live_events.json football_scraper.log
        git diff --staged --quiet || git commit -m "🚀 LUCILAND Auto-update: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
