# A descriptive name for your workflow
name: en2en

# --- TRIGGERS ---
on:
  # Allows you to run this workflow manually from the Actions tab in GitHub.
  workflow_dispatch:

  # Runs the workflow on a schedule.
  schedule:
    # This is a CRON string that means "at minute 0 of every hour".
    - cron: '0 * * * *'

# --- JOBS ---
jobs:
  build-and-encrypt:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the encryptor script
      - name: Run En2en Service
        run: python comradicaloculiwersetyouts.py

      # Step 5: Upload the encrypted file as an artifact
      - name: Upload Encrypted Data Artifact
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact to be uploaded.
          name: encrypted-live-data
          # This path now specifically looks for a file with a 50-character name + .json
          # It will IGNORE other .json files like config.json or live_events.json
          path: ??????????????????????????????????????????????????.json
