# A descriptive name for your workflow
name: Encrypt and Deploy Live Data

# --- TRIGGERS ---
# This workflow will only run manually from the Actions tab in GitHub.
on:
  workflow_dispatch:

# --- JOBS ---
jobs:
  build-and-encrypt:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # Grant the workflow's token write permission to the repository's contents.
    permissions:
      contents: write

    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the encryptor script
      # IMPORTANT: Make sure this filename matches the name of your python script.
      - name: Run Encryptor Service
        run: python comradicaloculiwersetyouts.py

      # Step 5: Commit the new encrypted file to the repository
      - name: Commit encrypted file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The message for the commit
          commit_message: "chore: Auto-generate encrypted data"
          # The pattern of the file(s) to commit.
          file_pattern: "67d18f5b263505d3be8283897bb383f149a39dd35bf9563d43.json"
          # The user name and email for the commit
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
