# A descriptive name for your workflow
name: Encr
# --- TRIGGERS ---
on:
  # Allows you to run this workflow manually from the Actions tab in GitHub.
  workflow_dispatch:

  # Runs the workflow on a schedule.
  schedule:
    # This is a CRON string that means "at minute 0 of every hour".
    - cron: '0 * * * *'

# --- JOBS ---
jobs:
  build-and-encrypt:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the encryptor script
      - name: Run Encryptor Service
        run: python comradicaloculiwersetyouts.py  # Make sure this filename is correct

      # Step 5: Commit the new encrypted file to the repository
      # This action finds the new file, adds it, commits it, and pushes it to your repo.
      - name: Commit encrypted file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The message for the commit
          commit_message: "chore: Auto-generate encrypted data"
          # The pattern of the file(s) to commit.
          # This specifically targets the 50-character JSON file.
          file_pattern: "??????????????????????????????????????????????????.json"
          # The user name and email for the commit
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
